name       : python-importlib-resources
version    : 3.3.1
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/i/importlib_resources/importlib_resources-3.3.1.tar.gz : 0ed250dbd291947d1a298e89f39afcc477d5a6624770503034b72588601bcc05
homepage   : https://github.com/python/importlib_resources
license    : Apache-2.0
component  : programming.python
summary    : importlib_resources is a backport of Python standard library importlib.resources module for older Pythons
description: |
    importlib_resources is a backport of Python standard library importlib.resources module for Python 2.7, and 3.6 through 3.8
builddeps  :
    - python-setuptools-scm
    - python-toml
rundeps    :
    - python-zipp
build      : |
    %python3_setup
install    : |
    %python3_install
