name       : python-importlib-resources
version    : 3.3.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/e1/bf/b40e6ecb611fa3be5b0ecae7b37ae1fa0d8df3146477ec0a554e8f62c976/importlib_resources-3.3.1.tar.gz : 0ed250dbd291947d1a298e89f39afcc477d5a6624770503034b72588601bcc05
license    : Apache-2.0
component  : programming.python
summary    : importlib_resources is a backport of Python standard library importlib.resources module for Python 2.7, and 3.6 through 3.8
description: |
    importlib_resources is a backport of Python standard library importlib.resources module for Python 2.7, and 3.6 through 3.8
builddeps  :
    - python-setuptools
    - python-setuptools-scm
    - python-toml
rundeps    :
    - python-pathlib2
    - python-typing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
