name       : python-importlib-resources
version    : 1.0.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/83/a4/ce09af12e1a91b5b77cefc893ef5054619553734c5b42f143d93ed581744/importlib_resources-1.0.2.tar.gz : d3279fd0f6f847cced9f7acc19bd3e5df54d34f93a2e7bb5f238f81545787078
license    : Python-2.0
component  : programming.python
summary    : importlib_resources is a backport of Python 3.7’s standard library importlib.resources module for Python 2.7.
description: |
    importlib_resources is a backport of Python 3.7’s standard library importlib.resources module for Python 2.7. 
builddeps  :
    - python-setuptools
    - python-wheel
rundeps    :
    - python-pathlib2
    - python-typing
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install   
